DROP TABLE IF EXISTS cars;
CREATE TABLE cars (
    APTREMAKEID INTEGER PRIMARY KEY AUTOINCREMENT,
    Car TEXT,
    Nation TEXT,
    Price INTEGER,
    Repair TEXT,
    Mileage INTEGER,
    Weight INTEGER
);
